# docker compose up --build --no-log-prefix
services:
  detect-one-tool:
    build: .
    models:
      qwen2_5_tiny:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_QWEN2_5_TINY
      qwen2_5_small:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_QWEN2_5_SMALL
      qwen2_5_medium:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_QWEN2_5_MEDIUM
      qwen3_tiny:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_QWEN3_TINY
      lucy:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_LUCY


models:
  qwen2_5_tiny:
    model: ai/qwen2.5:0.5B-F16
  qwen2_5_small:
    model: ai/qwen2.5:1.5B-F16
  qwen2_5_medium:
    model: ai/qwen2.5:3B-F16
  qwen3_tiny:
    model: ai/qwen3:0.6B-F16
  lucy:
    model: hf.co/menlo/lucy-128k-gguf:q4_k_m

